{
 "title": "energy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SOC",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "state_of_charge", "legendFormat": "__auto" }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "voltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "state_of_charge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "consumed Ah",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "targets": [
    { "expr": "400+consumed_ah", "legendFormat": "Ah" },
    { "expr": "state_of_charge", "legendFormat": "%" }
   ]
  },
  {
   "title": "inst remaining",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((state_of_charge/100*400)/-(current<0))*60",
     "legendFormat": "remaining"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "power consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "power", "legendFormat": "__auto" },
    { "expr": "0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "current", "legendFormat": "current" },
    { "expr": "voltage", "legendFormat": "voltage" },
    { "expr": "0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    { "expr": "time_remaining > 0", "legendFormat": "reported" },
    {
     "expr": "((state_of_charge/100*400)/-(current<0))*60 < 50*24*10",
     "legendFormat": "instant time remaining"
    },
    {
     "expr": "((avg_over_time(state_of_charge[1h])/100*400)/-(avg_over_time(current[1h])<0))*60 < 60*24*10",
     "legendFormat": "avg hourly"
    },
    {
     "expr": "((400 - state_of_charge/100*400)/(current>0))*60",
     "legendFormat": "instant time to full"
    }
   ]
  },
  {
   "title": "disagreeing?",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "targets": [
    { "expr": "400+consumed_ah", "legendFormat": "according to consumed" },
    { "expr": "(state_of_charge/100)*400", "legendFormat": "according to soc" },
    {
     "expr": "(\n    (voltage < 10)*0+0 or\n    (voltage >= 10.0 and voltage < 12.0)*0 +.09 or\n    (voltage >= 12.0 and voltage < 12.5)*0 +.09 or\n    (voltage >= 12.5 and voltage < 12.8)*0 +.14 or\n    (voltage >= 12.8 and voltage < 12.9)*0 +.17 or\n    (voltage >= 12.9 and voltage < 13.0)*0 +.20 or\n    (voltage >= 13.0 and voltage < 13.1)*0 +.30 or\n    (voltage >= 13.1 and voltage < 13.2)*0 +.40 or\n    (voltage >= 13.2 and voltage < 13.3)*0 +.70 or\n    (voltage >= 13.3 and voltage < 13.4)*0 +.90 or\n    (voltage >= 13.4 and voltage < 13.6)*0 +.99 or\n    (voltage >= 13.6)*0+1\n) * 400",
     "legendFormat": "according to voltage"
    },
    {
     "expr": "sum_over_time(current[1h]) / count_over_time(current[1h])",
     "legendFormat": "according to integral"
    }
   ]
  },
  {
   "title": "SOC - Ah SOC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "state_of_charge - ((400+consumed_ah)/400*100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}