#! /bin/sh

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9
bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9
#bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc config top_padding 22

#heheheh
bspc rule -a "*" floating=on
